### ISSUE TITLE
Developer interface

### ISSUE THREAD

**Issue by akhmerov** [executablebooks/sphinx-thebe#2] opened 2020-06-18 07:58 UTC
Right now the extension requires the developer to provide an extra markup (thebelab class). This isn't compatible with most existing code: I think there are now some 3-5 different sphinx extensions that interface thebelab, each in their own way.

I propose to instead make all code blocks belong to thebelab out of the box. This is to avoid imposing a new pattern on the users.

To address the needs of extension developers that want to migrate to sphinx-thebelab we could document how to specify an own selector for thebelab and thebelab output.

That way existing extensions that already implement thebelab support would hopefully be able to switch with a few lines in their own configuration rather than demanding a rewrite from the users.

**Comment by choldgraf** [comment] 2020-06-18 15:21
I think this should actually be pretty easy to do already, by changing the "selector" config (that I just realized is not documented). Right now selector looks for `.thebelab` but if you wanted to select *all* code blocks, you could just do:

```
thebelab_config = {
  "selector": "div.highlight"
}
```

and it'd select all code blocks.

I was first thinking of a thebelab-specific selector just to avoid people having unexpected behavior (e.g. many pages may have code blocks that are _meant_ to be static and non-runnable)

**Comment by choldgraf** [comment] 2020-06-18 15:27
Actually, I was thinking about expanding this "selector" interface a little bit to be three things:

`selector`, `selector-code`, `selector-output`.

Basically, the assumption is that `selector` applies to the containing element of the actual code (e.g. there's usually a `div.highlight` element around the `pre` code). That way, `selector` is the "parent" element, `selector-code` can be specified as an HTML selector *within* the parent element, and `selector-output` would serve the same purpose for marking something as the "output preview" when thebelab is initialized.

This seems important because Thebelab actually **replaces** the things that it is run on, so we'd lose extra classes and stuff like this. By having a "parent selector" and "code selector" we could avoid that. WDYT?

**Comment by choldgraf** [comment] 2020-06-18 21:00
OK - I just implemented this functionality to see how it feels. Want to check out the docs and see if this could nail all of your usecases? I will do the same for sphinx-book-theme.

https://executablebooks.github.io/sphinx-thebelab/

**Comment by akhmerov** [comment] 2020-06-21 14:23
> I was first thinking of a thebelab-specific selector just to avoid people having unexpected behavior (e.g. many pages may have code blocks that are meant to be static and non-runnable)

Ah gotcha, it's mostly a matter of documentation then.

> Actually, I was thinking about expanding this "selector" interface a little bit to be three things...

Hm, if we're already talking about jquery selectors (are we?), then AFAIU, they can already capture child or sibling relationship. Therefore documenting how to provide a selector that is as specific as possible would be sufficient.

**Comment by choldgraf** [comment] 2020-06-21 15:10
@akhmerov check out the docs, the functionality should not be documented. Wdyt?

**Comment by akhmerov** [comment] 2020-06-22 13:45
Thanks, I understand things better now.

Re: nested selectors. Does it make a difference for the user or an extension developer? Both the extension developer and the end user can wrap their thebelab elements into other containers to not lose styling. With your proposed selector structure they would still need nested containers.

I am also wondering about two things: 

- Making the output selector a *child* of the main selector is different from thebelab's own options. Is this to allow output to precede code?
- The initialization code seems to be doing almost the same work as done by thebelab's own initialization. Specifically I'm looking at [this segment](https://github.com/executablebooks/sphinx-thebelab/blob/master/sphinx_thebelab/_static/thebelab.js#L23-L43) in sphinx-thebelab vs [this segment](https://github.com/minrk/thebelab/blob/master/src/thebelab.js#L142-L170) in thebelab. The main added functionality that I see done in sphinx-thebelab is adding the data-language for codemirror. Wouldn't it make sense to upstream this to thebelab itself?

**Comment by choldgraf** [comment] 2020-06-22 18:50
good points about the nesting selectors etc. Are you suggesting that it would be preferable to just have two selectors: one for inputs and one for the output? To that extent, my main question is:

How do we ensure that the selector for the output is unique to each input? I was using a "parent" selector first so that we can easily find the output relative to the input.

> The initialization code seems to be doing almost the same work as done by thebelab's own initialization.

the main differences are:

thebelab needs the `data-language` attribute to handle the codemirror style, I think. We can't assume that attribute is already there, so the `sphinx-thebelab` code adds it.

thebelab assumes that the output is the *next HTML element*, whereas we can't assume that is the case, so `sphinx-thebelab` uses an HTML *selector* for the output, and then *moves* it just after the input cell, so that thebelab will find it. Do you know of another way to have thebelab find the output without requiring us to move it just after the cell?

**Comment by akhmerov** [comment] 2020-06-23 09:47
> How do we ensure that the selector for the output is unique to each input? I was using a "parent" selector first so that we can easily find the output relative to the input.

Under which conditions do we expect the input and output to not appear sequentially? I know that jupyter-sphinx allows interchanging them (I think for historical reasons, not sure if anyone actually used that), is there anything else?

> thebelab needs the data-language attribute to handle the codemirror style, I think. We can't assume that attribute is already there, so the sphinx-thebelab code adds it.

Thanks for the clarification. Could thebelab do it *after* initializing the kernel?

> Do you know of another way to have thebelab find the output without requiring us to move it just after the input?

I think modifying or extensing thebelab itself would be the most promising approach.

**Comment by choldgraf** [comment] 2020-06-23 18:50
> Under which conditions do we expect the input and output to not appear sequentially

I think the main problem is that Sphinx generally wraps a code block in another div, so they aren't technically sequential. E.g. it's often something like:

```
<div class="highlight">
  <pre>code</pre>
</div>
<div class="output">
</div>
```

and since Thebelab selects the `pre`, it *technically* doesn't have any siblings. Though I haven't tested this much in Thebelab, maybe it would still work?

> Could thebelab do it after initializing the kernel?

I'm not sure, TBH I don't understand the guts of Thebelab super well 😬

**Comment by akhmerov** [comment] 2020-06-23 20:05
> and since Thebelab selects the pre, it technically doesn't have any siblings. 

Thebelab doesn't need to select the innermost `pre` tag, it may also select the enclosing `div.highlight`. Would this be sufficient to take care of user needs?

**Comment by choldgraf** [comment] 2020-06-23 20:11
ah but if it selects the `div.highlight`, then it will replace it, which means that people couldn't do things like add classes to it (since those are added at the `div.highlight` level, not the `pre` level

**Comment by akhmerov** [comment] 2020-06-24 11:03
Got it. Took a looong while to sink in.

I think the enclosing selector also seems to be something that thebelab could incorporate without breaking backwards compatibility. Should I move also that discussion upstream?

**Comment by choldgraf** [comment] 2021-08-28 15:45
I am going to close this one as I don't think there's anything more actionable in it. But if there is something unresolved could you open an issue that's specific to that new thing?

**Closed by choldgraf** 2021-08-28 15:45 UTC

**Comment by akhmerov** [comment] 2021-08-28 16:39
Indeed, executablebooks/thebe#238 covers the remaining actionable points. Thanks!
