### ISSUE TITLE
Your sphinx documentation is not working

### ISSUE THREAD

**Issue by sedv8808** [executablebooks/sphinx-thebe#53] opened 2022-05-12 20:59 UTC
I am trying to run r-kernel thebe. So I came up to your site. However, your own documentation is giving me the same error I am currently facing:

```
NameError: name 'library' is not defined
```

Although you have specified an R kernel, it is running on Jupyter... Any ideas or workarounds would be highly appreciated

**Comment by choldgraf** [comment] 2023-01-05 13:46
thanks for noticing - closing this one as a duplicate of:

- https://github.com/executablebooks/sphinx-thebe/issues/43

**Closed** 2023-01-17 11:13 UTC
